apiVersion: v1
kind: Service
metadata:
  name: thumbnail-api
spec:
  type: {{ .Values.service.api.type }}
  selector:
    app: thumbnail-api
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 8000
